# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downlink.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='downlink.proto',
  package='iot',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64ownlink.proto\x12\x03iot\"A\n\x08\x44ownlink\x12\x0e\n\x06\x66_port\x18\x01 \x01(\x05\x12\x13\n\x0b\x66rm_payload\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\t\",\n\tDownlinks\x12\x1f\n\x08\x64ownlink\x18\x01 \x03(\x0b\x32\r.iot.Downlink'
)




_DOWNLINK = _descriptor.Descriptor(
  name='Downlink',
  full_name='iot.Downlink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_port', full_name='iot.Downlink.f_port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frm_payload', full_name='iot.Downlink.frm_payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='iot.Downlink.priority', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=88,
)


_DOWNLINKS = _descriptor.Descriptor(
  name='Downlinks',
  full_name='iot.Downlinks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='downlink', full_name='iot.Downlinks.downlink', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=134,
)

_DOWNLINKS.fields_by_name['downlink'].message_type = _DOWNLINK
DESCRIPTOR.message_types_by_name['Downlink'] = _DOWNLINK
DESCRIPTOR.message_types_by_name['Downlinks'] = _DOWNLINKS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Downlink = _reflection.GeneratedProtocolMessageType('Downlink', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLINK,
  '__module__' : 'downlink_pb2'
  # @@protoc_insertion_point(class_scope:iot.Downlink)
  })
_sym_db.RegisterMessage(Downlink)

Downlinks = _reflection.GeneratedProtocolMessageType('Downlinks', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLINKS,
  '__module__' : 'downlink_pb2'
  # @@protoc_insertion_point(class_scope:iot.Downlinks)
  })
_sym_db.RegisterMessage(Downlinks)


# @@protoc_insertion_point(module_scope)
