# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: headers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='headers.proto',
  package='iot',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rheaders.proto\x12\x03iot\"D\n\x07Headers\x12\x15\n\rAuthorization\x18\x01 \x01(\t\x12\x0e\n\x06\x41\x63\x63\x65pt\x18\x02 \x01(\t\x12\x12\n\nUser_Agent\x18\x03 \x01(\t'
)




_HEADERS = _descriptor.Descriptor(
  name='Headers',
  full_name='iot.Headers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Authorization', full_name='iot.Headers.Authorization', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Accept', full_name='iot.Headers.Accept', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='User_Agent', full_name='iot.Headers.User_Agent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Headers'] = _HEADERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Headers = _reflection.GeneratedProtocolMessageType('Headers', (_message.Message,), {
  'DESCRIPTOR' : _HEADERS,
  '__module__' : 'headers_pb2'
  # @@protoc_insertion_point(class_scope:iot.Headers)
  })
_sym_db.RegisterMessage(Headers)


# @@protoc_insertion_point(module_scope)
